agent: "MAPPO"
env_name: "Drones"
env_id: "SimpleSpreadAviary3D"
env_seed: 1
obs_type: "kin"
act_type: "vel"
num_drones: 3
num_landmarks: 3
world_size: 2.0
collision_radius: 0.15
collision_penalty: 1.0
flight_height: 1.0
render: False
sleep: 0.01
continuous_action: True
learner: "MAPPO_Learner"
policy: "Gaussian_MAAC_Policy"
representation: "Basic_MLP"
vectorize: "SubprocVecMultiAgentEnv"
runner: "MARL"

# recurrent settings
use_rnn: False
rnn: "GRU"
fc_hidden_sizes: [64, 64, 64]
recurrent_hidden_size: 64
N_recurrent_layers: 1
dropout: 0
normalize: "LayerNorm"
initialize: "orthogonal"
gain: 0.01

# network
representation_hidden_size: [128, ]
actor_hidden_size: [128, 128]
critic_hidden_size: [128, 128]
activation: "relu"
activation_action: "tanh"

# multi-agent
use_parameter_sharing: True
use_actions_mask: False

seed: 2
parallels: 16
buffer_size: 800
n_epochs: 5
n_minibatch: 2
learning_rate: 0.0005
weight_decay: 0

vf_coef: 0.5
ent_coef: 0.01
target_kl: 0.25
clip_range: 0.2
clip_type: 1
gamma: 0.99

# tricks
use_linear_lr_decay: True
end_factor_lr_decay: 0.1
use_global_state: True
use_value_clip: True
value_clip_range: 0.2
use_value_norm: True
use_huber_loss: True
huber_delta: 10.0
use_advnorm: True
use_gae: True
gae_lambda: 0.95
use_grad_clip: True
grad_clip_norm: 10.0

max_episode_steps: 1600
running_steps: 10000000
eval_interval: 100000
test_episode: 5

log_dir: "logs/mappo/"
model_dir: "models/mappo/"
