agent: "MAPPO"
env_name: "DroneSpreadPlanner3D"
env_id: "SimpleSpreadDrones3DPlanner"
env_seed: 1
continuous_action: True
learner: "MAPPO_Learner"
policy: "Gaussian_MAAC_Policy"
representation: "Basic_MLP"
vectorize: "SubprocVecMultiAgentEnv"
runner: "MARL"

# recurrent settings
use_rnn: False
rnn: "GRU"
fc_hidden_sizes: [64, 64, 64]
recurrent_hidden_size: 64
N_recurrent_layers: 1
dropout: 0
normalize: "LayerNorm"
initialize: "orthogonal"
gain: 0.01

# network
representation_hidden_size: [256, ]
actor_hidden_size: [256, 256]
critic_hidden_size: [256, 256]
activation: "relu"
activation_action: "tanh"

# multi-agent
use_parameter_sharing: True
use_actions_mask: False

seed: 1
parallels: 16
buffer_size: 1200
n_epochs: 5
n_minibatch: 4
learning_rate: 0.0007
weight_decay: 0

vf_coef: 0.5
ent_coef: 0.02
target_kl: 0.25
clip_range: 0.2
clip_type: 1
gamma: 0.99

# tricks
use_linear_lr_decay: True
end_factor_lr_decay: 0.1
use_global_state: True
use_value_clip: True
value_clip_range: 0.2
use_value_norm: True
use_huber_loss: True
huber_delta: 10.0
use_advnorm: True
use_gae: True
gae_lambda: 0.95
use_grad_clip: True
grad_clip_norm: 10.0

running_steps: 20000000
eval_interval: 100000
test_episode: 5

log_dir: "logs/mappo/"
model_dir: "models/mappo/"
