agent: "PPO"
env_name: "Drone"
env_id: "NavigateAviary"
env_seed: 1
obs_type: "kin"
act_type: "vel"
num_drones: 1
record: False
render: False
sleep: 0.01
obstacles: True
max_episode_steps: 600
vectorize: "DummyVecEnv"
learner: "PPO_Learner"
policy: "Gaussian_AC"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [256, ]
actor_hidden_size: [256, 256]
critic_hidden_size: [256, 256]
activation: "leaky_relu"
activation_action: "tanh"

seed: 79811
parallels: 10
running_steps: 3000000
horizon_size: 512
n_epochs: 4
n_minibatch: 8
learning_rate: 0.0003

vf_coef: 0.25
ent_coef: 0.01
target_kl: 0.25
kl_coef: 1.0
clip_range: 0.2
gamma: 0.99
use_gae: True
gae_lambda: 0.95
use_advnorm: True

use_grad_clip: True
clip_type: 1
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: True
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

eval_interval: 50000
test_episode: 5
log_dir: "logs/ppo/"
model_dir: "models/ppo/"
